; PlatformIO Project Configuration File
;
; Branch test-run: firmware minimal (Modbus + mock), tanpa DHT22/OLED.
; Tidak butuh library eksternal — hanya core espressif8266.

[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
